// <auto-generated />
using System;
using EducacionalAPIConexaoDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducacionalAPIConexaoDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230204174650_novasColunasEtabelas")]
    partial class novasColunasEtabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EducacionalAPIConexaoDB.Models.Educacional", b =>
                {
                    b.Property<int>("EducacionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CodInstituicao")
                        .HasColumnType("int");

                    b.Property<int>("EducacionalCod")
                        .HasColumnType("int");

                    b.Property<string>("NomeInstituicao")
                        .HasColumnType("longtext");

                    b.HasKey("EducacionalId");

                    b.ToTable("Educacionais");
                });
#pragma warning restore 612, 618
        }
    }
}
